In [18]:
import pandas as pd
import numpy as np
from sklearn import svm, datasets
from sklearn.model_selection import cross_val_score

In [8]:
iris = datasets.load_iris()

In [9]:
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df['Flower'] = iris.target
df['Flower'] = df['Flower'].apply(lambda x: iris.target_names[x])

In [14]:
# Manual Approach:

cross_val_score(svm.SVC(kernel='linear', C=10, gamma='auto'), iris.data, iris.target, cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [15]:
cross_val_score(svm.SVC(kernel='rbf', C=10, gamma='auto'), iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [16]:
cross_val_score(svm.SVC(kernel='rbf', C=20, gamma='auto'), iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [19]:
# Alternative approach:

kernels = ['linear', 'rbf']
C = [1, 10, 20]
avg_scr = {}
for k in kernels:
    for x in C:
        cvs = cross_val_score(svm.SVC(kernel=k, C=x, gamma='auto'), iris.data, iris.target, cv=5)
        avg_scr[k+'_'+str(x)] = np.average(cvs)

avg_scr

{'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666,
 'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668}